version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ARC
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile dev]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
             eb use ARC-dev --profile dev
             eb deploy -v --staged --profile dev
             echo $CIRCLE_BUILD_NUM
             echo $CIRCLE_JOB
             echo $CIRCLE_PR_NUMBER
             echo $CIRCLE_PREVIOUS_BUILD_NUM
             echo $CIRCLE_WORKFLOW_ID
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master